//! Autogenerated weights for pallet_xode_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 43.1.0
//! DATE: 2025-11-25, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `hgminerva-vivobook`, CPU: `13th Gen Intel(R) Core(TM) i9-13900H`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// target/release/xode-node
// benchmark
// pallet
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --pallet
// pallet-xode-staking
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// ./pallets/staking/src/weights.rs
// --template
// ./pallets/staking/src/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_xode_staking.
pub trait WeightInfo {
  fn register_candidate() -> Weight;
  fn bond_candidate() -> Weight;
  fn set_commission_of_candidate() -> Weight;
  fn leave_candidate() -> Weight;
  fn stake_candidate() -> Weight;
  fn unstake_candidate() -> Weight;
  fn offline_candidate() -> Weight;
  fn online_candidate() -> Weight;
  fn bond_correction() -> Weight;
}

/// Weights for pallet_xode_staking using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn register_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `27`
    //  Estimated: `9187`
    // Minimum execution time: 9_422_000 picoseconds.
    Weight::from_parts(9_795_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn bond_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 25_590_000 picoseconds.
    Weight::from_parts(26_115_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn set_commission_of_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 11_391_000 picoseconds.
    Weight::from_parts(12_123_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn leave_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `219`
    //  Estimated: `9187`
    // Minimum execution time: 10_783_000 picoseconds.
    Weight::from_parts(11_633_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  /// Storage: `XodeStaking::Delegations` (r:1 w:1)
  /// Proof: `XodeStaking::Delegations` (`max_values`: None, `max_size`: Some(4842), added: 7317, mode: `MaxEncodedLen`)
  fn stake_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 62_467_000 picoseconds.
    Weight::from_parts(65_009_000, 9187)
      .saturating_add(T::DbWeight::get().reads(2_u64))
      .saturating_add(T::DbWeight::get().writes(2_u64))
  }
  /// Storage: `XodeStaking::Delegations` (r:1 w:1)
  /// Proof: `XodeStaking::Delegations` (`max_values`: None, `max_size`: Some(4842), added: 7317, mode: `MaxEncodedLen`)
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn unstake_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `300`
    //  Estimated: `9187`
    // Minimum execution time: 40_944_000 picoseconds.
    Weight::from_parts(42_495_000, 9187)
      .saturating_add(T::DbWeight::get().reads(2_u64))
      .saturating_add(T::DbWeight::get().writes(2_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn offline_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 13_451_000 picoseconds.
    Weight::from_parts(13_986_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn online_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 13_771_000 picoseconds.
    Weight::from_parts(14_293_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn bond_correction() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 13_931_000 picoseconds.
    Weight::from_parts(15_167_000, 9187)
      .saturating_add(T::DbWeight::get().reads(1_u64))
      .saturating_add(T::DbWeight::get().writes(1_u64))
  }
}


// For backwards compatibility and tests
impl WeightInfo for () {
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn register_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `27`
    //  Estimated: `9187`
    // Minimum execution time: 9_422_000 picoseconds.
    Weight::from_parts(9_795_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn bond_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 25_590_000 picoseconds.
    Weight::from_parts(26_115_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn set_commission_of_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 11_391_000 picoseconds.
    Weight::from_parts(12_123_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn leave_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `219`
    //  Estimated: `9187`
    // Minimum execution time: 10_783_000 picoseconds.
    Weight::from_parts(11_633_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  /// Storage: `XodeStaking::Delegations` (r:1 w:1)
  /// Proof: `XodeStaking::Delegations` (`max_values`: None, `max_size`: Some(4842), added: 7317, mode: `MaxEncodedLen`)
  fn stake_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 62_467_000 picoseconds.
    Weight::from_parts(65_009_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(2_u64))
      .saturating_add(RocksDbWeight::get().writes(2_u64))
  }
  /// Storage: `XodeStaking::Delegations` (r:1 w:1)
  /// Proof: `XodeStaking::Delegations` (`max_values`: None, `max_size`: Some(4842), added: 7317, mode: `MaxEncodedLen`)
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn unstake_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `300`
    //  Estimated: `9187`
    // Minimum execution time: 40_944_000 picoseconds.
    Weight::from_parts(42_495_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(2_u64))
      .saturating_add(RocksDbWeight::get().writes(2_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn offline_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 13_451_000 picoseconds.
    Weight::from_parts(13_986_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn online_candidate() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `108`
    //  Estimated: `9187`
    // Minimum execution time: 13_771_000 picoseconds.
    Weight::from_parts(14_293_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
  /// Storage: `XodeStaking::ProposedCandidates` (r:1 w:1)
  /// Proof: `XodeStaking::ProposedCandidates` (`max_values`: Some(1), `max_size`: Some(7702), added: 8197, mode: `MaxEncodedLen`)
  fn bond_correction() -> Weight {
    // Proof Size summary in bytes:
    //  Measured:  `185`
    //  Estimated: `9187`
    // Minimum execution time: 13_931_000 picoseconds.
    Weight::from_parts(15_167_000, 9187)
      .saturating_add(RocksDbWeight::get().reads(1_u64))
      .saturating_add(RocksDbWeight::get().writes(1_u64))
  }
}
